name: ffitest
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  ffi: ^2.0.2

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: 'bin/generated_bindings.dart'
  headers:
    entry-points:
      - 'ffi/lib.h'